name: 'Close stale PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'Stale PRs will be automatically closed to keep this repo clean. If there is no activity on this PR in the next 7 days, this PR will be closed.'
